<?php

namespace Ampeco\OmnipayKapitalbank\Message;

class CreateCardResponse extends Response
{
    public function isSuccessful() : bool
    {
        return parent::isSuccessful(); // TODO: Change the autogenerated stub
    }
}
